 package com.htdz.def.view;


import java.util.List;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import com.htdz.def.dbmodel.TareaInfo;

/**
 * TareaInfo generated by hbm2java
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class GpsAreaInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private List<TareaInfo> areaInfoList;
	private List<PushInfo> gpsDataList;

}
