package com.htdz.def.view;

import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * TareaInfo generated by hbm2java
 */

@Data
@AllArgsConstructor
@NoArgsConstructor
public class PushInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer did;// 设备ID
	private String equipId;// deviceSn 设备号
	private Integer msgType;// 推送消息类型 0表示位置数据，1表示警情数据，：2表示状态数据
	private Integer alarmtype;// 警情类型
	private Date datetime;// UTC时间
	private Date rcvTime;
	private Double lat;
	private Double lng;
	private String speed;
	private String direction;
	private Integer ranges;
	private String onlinestatus;// 在线状态
	private String title;// liteFamliyApp 提醒内容
}
