package com.htdz.def.view;

import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * TareaInfo generated by hbm2java
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Rail implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String deviceSn;
	private String areaid;
	private Date collectDatetime;
	private Boolean outSide;
	private Boolean isNotity;
}
